(*
    Example datasets metadata from Mathematica and R
    Copyright (C) 2021  Anton Antonov

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.

    Written by Anton Antonov,
    antononcube @@@ posteo .. net,
    Windermere, Florida, USA.
*)

(* :Title: ExampleDatasetsMetadata *)
(* :Context: Global` *)
(* :Author: Anton Antonov *)
(* :Date: 2021-10-07 *)

(* :Package Version: 1.0 *)
(* :Mathematica Version: *)
(* :Copyright: (c) 2021 Anton Antonov *)
(* :Keywords: *)
(* :Discussion:

   It is a good idea to include the code with which the metadata was derived.

*)

dsDatasetMetadata = Dataset[{<|"Package" -> "Statistics", "Item" -> "AirlinePassengerMiles",
  "Title" -> "Airline Passenger Miles", "RowsCount" -> 24, "ColumnsCount" -> 1,
  "NumericColumnsCount" -> 1, "CharacterColumnsCount" -> 0|>,
  <|"Package" -> "Statistics", "Item" -> "AirplaneGlass", "Title" -> "Airplane Glass",
    "RowsCount" -> 31, "ColumnsCount" -> 1, "NumericColumnsCount" -> 1,
    "CharacterColumnsCount" -> 0|>, <|"Package" -> "Statistics",
    "Item" -> "AnimalWeights", "Title" -> "Animal Weights", "RowsCount" -> 28,
    "ColumnsCount" -> 3, "NumericColumnsCount" -> 2, "CharacterColumnsCount" -> 1|>,
  <|"Package" -> "Statistics", "Item" -> "AnorexiaTreatment",
    "Title" -> "Anorexia Treatment", "RowsCount" -> 72, "ColumnsCount" -> 3,
    "NumericColumnsCount" -> 2, "CharacterColumnsCount" -> 1|>,
  <|"Package" -> "Statistics", "Item" -> "AnscombeRegressionLines",
    "Title" -> "Anscombe Regression Lines", "RowsCount" -> 11, "ColumnsCount" -> 8,
    "NumericColumnsCount" -> 8, "CharacterColumnsCount" -> 0|>,
  <|"Package" -> "Statistics", "Item" -> "AustraliaAIDS", "Title" -> "Australia AIDS",
    "RowsCount" -> 2843, "ColumnsCount" -> 7, "NumericColumnsCount" -> 3,
    "CharacterColumnsCount" -> 4|>, <|"Package" -> "Statistics",
    "Item" -> "AustraliaRainfall", "Title" -> "Australia Rainfall", "RowsCount" -> 47,
    "ColumnsCount" -> 1, "NumericColumnsCount" -> 1, "CharacterColumnsCount" -> 0|>,
  <|"Package" -> "Statistics", "Item" -> "Baboon", "Title" -> "Baboon",
    "RowsCount" -> 152, "ColumnsCount" -> 2, "NumericColumnsCount" -> 2,
    "CharacterColumnsCount" -> 0|>, <|"Package" -> "Statistics",
    "Item" -> "BatchChemicalProcessYields", "Title" -> "BatchChemicalProcessYields",
    "RowsCount" -> 70, "ColumnsCount" -> 1, "NumericColumnsCount" -> 1,
    "CharacterColumnsCount" -> 0|>, <|"Package" -> "Statistics",
    "Item" -> "BeaverBodyTemperatures", "Title" -> "Beaver Body Temperatures",
    "RowsCount" -> 114, "ColumnsCount" -> 4, "NumericColumnsCount" -> 4,
    "CharacterColumnsCount" -> 0|>, <|"Package" -> "Statistics",
    "Item" -> "BelgianCalls", "Title" -> "Belgian Calls", "RowsCount" -> 24,
    "ColumnsCount" -> 2, "NumericColumnsCount" -> 2, "CharacterColumnsCount" -> 0|>,
  <|"Package" -> "Statistics", "Item" -> "BiochemicalOxygenDemand",
    "Title" -> "Biochemical Oxygen Demand", "RowsCount" -> 6, "ColumnsCount" -> 2,
    "NumericColumnsCount" -> 2, "CharacterColumnsCount" -> 0|>,
  <|"Package" -> "Statistics", "Item" -> "BirthWeightRisk",
    "Title" -> "Birth Weight Risk", "RowsCount" -> 189, "ColumnsCount" -> 11,
    "NumericColumnsCount" -> 11, "CharacterColumnsCount" -> 0|>,
  <|"Package" -> "Statistics", "Item" -> "BlackCherryTrees",
    "Title" -> "Black Cherry Trees", "RowsCount" -> 31, "ColumnsCount" -> 3,
    "NumericColumnsCount" -> 3, "CharacterColumnsCount" -> 0|>,
  <|"Package" -> "Statistics", "Item" -> "BoforsSteel", "Title" -> "Bofors Steel",
    "RowsCount" -> 389, "ColumnsCount" -> 1, "NumericColumnsCount" -> 1,
    "CharacterColumnsCount" -> 0|>, <|"Package" -> "Statistics", "Item" -> "BoilingAlps",
    "Title" -> "Boiling Alps", "RowsCount" -> 17, "ColumnsCount" -> 2,
    "NumericColumnsCount" -> 2, "CharacterColumnsCount" -> 0|>,
  <|"Package" -> "Statistics", "Item" -> "BoneMarrowLeukemia",
    "Title" -> "Bone Marrow Leukemia", "RowsCount" -> 137, "ColumnsCount" -> 22,
    "NumericColumnsCount" -> 22, "CharacterColumnsCount" -> 0|>,
  <|"Package" -> "Statistics", "Item" -> "BoneMarrowTransplants",
    "Title" -> "Bone Marrow Transplants", "RowsCount" -> 101, "ColumnsCount" -> 3,
    "NumericColumnsCount" -> 3, "CharacterColumnsCount" -> 0|>,
  <|"Package" -> "Statistics", "Item" -> "BostonHomes", "Title" -> "Boston Homes",
    "RowsCount" -> 506, "ColumnsCount" -> 14, "NumericColumnsCount" -> 14,
    "CharacterColumnsCount" -> 0|>, <|"Package" -> "Statistics", "Item" -> "BuffaloSnow",
    "Title" -> "Buffalo Snow", "RowsCount" -> 63, "ColumnsCount" -> 1,
    "NumericColumnsCount" -> 1, "CharacterColumnsCount" -> 0|>,
  <|"Package" -> "Statistics", "Item" -> "Cabbages", "Title" -> "Cabbages",
    "RowsCount" -> 60, "ColumnsCount" -> 4, "NumericColumnsCount" -> 2,
    "CharacterColumnsCount" -> 2|>, <|"Package" -> "Statistics",
    "Item" -> "CarStoppingDistances", "Title" -> "Car Stopping Distances",
    "RowsCount" -> 50, "ColumnsCount" -> 2, "NumericColumnsCount" -> 2,
    "CharacterColumnsCount" -> 0|>, <|"Package" -> "Statistics", "Item" -> "CementHeat",
    "Title" -> "Cement Heat", "RowsCount" -> 13, "ColumnsCount" -> 5,
    "NumericColumnsCount" -> 5, "CharacterColumnsCount" -> 0|>,
  <|"Package" -> "Statistics", "Item" -> "CeramicStrength",
    "Title" -> "Ceramic Strength", "RowsCount" -> 480, "ColumnsCount" -> 1,
    "NumericColumnsCount" -> 1, "CharacterColumnsCount" -> 0|>,
  <|"Package" -> "Statistics", "Item" -> "ChanningHouse", "Title" -> "Channing House",
    "RowsCount" -> 462, "ColumnsCount" -> 5, "NumericColumnsCount" -> 5,
    "CharacterColumnsCount" -> 0|>, <|"Package" -> "Statistics",
    "Item" -> "ChemicalProcessConcentrations",
    "Title" -> "ChemicalProcessConcentrations", "RowsCount" -> 197, "ColumnsCount" -> 1,
    "NumericColumnsCount" -> 1, "CharacterColumnsCount" -> 0|>,
  <|"Package" -> "Statistics", "Item" -> "ChemicalProcessTemperatures",
    "Title" -> "ChemicalProcessTemperatures", "RowsCount" -> 226, "ColumnsCount" -> 1,
    "NumericColumnsCount" -> 1, "CharacterColumnsCount" -> 0|>,
  <|"Package" -> "Statistics", "Item" -> "ChemicalProcessViscosityReadings",
    "Title" -> "ChemicalProcessViscosityReadings", "RowsCount" -> 310,
    "ColumnsCount" -> 1, "NumericColumnsCount" -> 1, "CharacterColumnsCount" -> 0|>,
  <|"Package" -> "Statistics", "Item" -> "ChickenWeight", "Title" -> "Chicken Weight",
    "RowsCount" -> 71, "ColumnsCount" -> 2, "NumericColumnsCount" -> 1,
    "CharacterColumnsCount" -> 1|>, <|"Package" -> "Statistics",
    "Item" -> "CopperLevels", "Title" -> "Copper Levels", "RowsCount" -> 24,
    "ColumnsCount" -> 1, "NumericColumnsCount" -> 1, "CharacterColumnsCount" -> 0|>,
  <|"Package" -> "Statistics", "Item" -> "CosmeticDeterioration",
    "Title" -> "Cosmetic Deterioration", "RowsCount" -> 95, "ColumnsCount" -> 3,
    "NumericColumnsCount" -> 3, "CharacterColumnsCount" -> 0|>,
  <|"Package" -> "Statistics", "Item" -> "CPUPerformance", "Title" -> "CPU Performance",
    "RowsCount" -> 209, "ColumnsCount" -> 10, "NumericColumnsCount" -> 8,
    "CharacterColumnsCount" -> 2|>, <|"Package" -> "Statistics",
    "Item" -> "CrabMeasures", "Title" -> "Crab Measures", "RowsCount" -> 200,
    "ColumnsCount" -> 8, "NumericColumnsCount" -> 6, "CharacterColumnsCount" -> 2|>,
  <|"Package" -> "Statistics", "Item" -> "Cushings", "Title" -> "Cushings",
    "RowsCount" -> 27, "ColumnsCount" -> 4, "NumericColumnsCount" -> 2,
    "CharacterColumnsCount" -> 2|>, <|"Package" -> "Statistics",
    "Item" -> "CyrtoideaeLength", "Title" -> "Cyrtoideae Length", "RowsCount" -> 100,
    "ColumnsCount" -> 1, "NumericColumnsCount" -> 1, "CharacterColumnsCount" -> 0|>,
  <|"Package" -> "Statistics", "Item" -> "DenmarkMelanoma",
    "Title" -> "Denmark Melanoma", "RowsCount" -> 205, "ColumnsCount" -> 7,
    "NumericColumnsCount" -> 7, "CharacterColumnsCount" -> 0|>,
  <|"Package" -> "Statistics", "Item" -> "DNaseAssay", "Title" -> "DNase Assay",
    "RowsCount" -> 176, "ColumnsCount" -> 3, "NumericColumnsCount" -> 2,
    "CharacterColumnsCount" -> 1|>, <|"Package" -> "Statistics",
    "Item" -> "EarthquakeWaitingTimes", "Title" -> "Earthquake Waiting Times",
    "RowsCount" -> 62, "ColumnsCount" -> 1, "NumericColumnsCount" -> 1,
    "CharacterColumnsCount" -> 0|>, <|"Package" -> "Statistics",
    "Item" -> "EconomicFluctuation", "Title" -> "Economic Fluctuation",
    "RowsCount" -> 16, "ColumnsCount" -> 7, "NumericColumnsCount" -> 7,
    "CharacterColumnsCount" -> 0|>, <|"Package" -> "Statistics",
    "Item" -> "EmployeeAttitude", "Title" -> "Employee Attitude", "RowsCount" -> 30,
    "ColumnsCount" -> 7, "NumericColumnsCount" -> 7, "CharacterColumnsCount" -> 0|>,
  <|"Package" -> "Statistics", "Item" -> "EsophagealCancer",
    "Title" -> "Esophageal Cancer", "RowsCount" -> 88, "ColumnsCount" -> 5,
    "NumericColumnsCount" -> 2, "CharacterColumnsCount" -> 3|>,
  <|"Package" -> "Statistics", "Item" -> "FatigueLifeFailures",
    "Title" -> "Fatigue Life Failures", "RowsCount" -> 22, "ColumnsCount" -> 1,
    "NumericColumnsCount" -> 1, "CharacterColumnsCount" -> 0|>,
  <|"Package" -> "Statistics", "Item" -> "FemaleHeightsAndWeights",
    "Title" -> "Female Heights And Weights", "RowsCount" -> 15, "ColumnsCount" -> 2,
    "NumericColumnsCount" -> 2, "CharacterColumnsCount" -> 0|>,
  <|"Package" -> "Statistics", "Item" -> "FiberStrength", "Title" -> "Fiber Strength",
    "RowsCount" -> 3000, "ColumnsCount" -> 1, "NumericColumnsCount" -> 1,
    "CharacterColumnsCount" -> 0|>, <|"Package" -> "Statistics", "Item" -> "FisherCats",
    "Title" -> "Fisher's Cats", "RowsCount" -> 144, "ColumnsCount" -> 3,
    "NumericColumnsCount" -> 2, "CharacterColumnsCount" -> 1|>,
  <|"Package" -> "Statistics", "Item" -> "FisherIris", "Title" -> "Fisher Iris",
    "RowsCount" -> 150, "ColumnsCount" -> 5, "NumericColumnsCount" -> 4,
    "CharacterColumnsCount" -> 1|>, <|"Package" -> "Statistics", "Item" -> "FlyAsh",
    "Title" -> "Fly Ash", "RowsCount" -> 211, "ColumnsCount" -> 1,
    "NumericColumnsCount" -> 1, "CharacterColumnsCount" -> 0|>,
  <|"Package" -> "Statistics", "Item" -> "Formaldehyde", "Title" -> "Formaldehyde",
    "RowsCount" -> 6, "ColumnsCount" -> 2, "NumericColumnsCount" -> 2,
    "CharacterColumnsCount" -> 0|>, <|"Package" -> "Statistics",
    "Item" -> "GAGUrineLevels", "Title" -> "GAG Urine Levels", "RowsCount" -> 314,
    "ColumnsCount" -> 2, "NumericColumnsCount" -> 2, "CharacterColumnsCount" -> 0|>,
  <|"Package" -> "Statistics", "Item" -> "GalaxyVelocity", "Title" -> "Galaxy Velocity",
    "RowsCount" -> 82, "ColumnsCount" -> 1, "NumericColumnsCount" -> 1,
    "CharacterColumnsCount" -> 0|>, <|"Package" -> "Statistics",
    "Item" -> "GasFurnaceData", "Title" -> "GasFurnaceData", "RowsCount" -> 296,
    "ColumnsCount" -> 2, "NumericColumnsCount" -> 2, "CharacterColumnsCount" -> 0|>,
  <|"Package" -> "Statistics", "Item" -> "GilgaiSoil", "Title" -> "Gilgai Soil",
    "RowsCount" -> 365, "ColumnsCount" -> 9, "NumericColumnsCount" -> 9,
    "CharacterColumnsCount" -> 0|>, <|"Package" -> "Statistics",
    "Item" -> "GreatBritanAutoDeaths", "Title" -> "Great Britan Auto Deaths",
    "RowsCount" -> 192, "ColumnsCount" -> 1, "NumericColumnsCount" -> 1,
    "CharacterColumnsCount" -> 0|>, <|"Package" -> "Statistics",
    "Item" -> "GuineaPigToothGrowth", "Title" -> "Guinea Pig Tooth Growth",
    "RowsCount" -> 60, "ColumnsCount" -> 3, "NumericColumnsCount" -> 2,
    "CharacterColumnsCount" -> 1|>, <|"Package" -> "Statistics", "Item" -> "Hodgkins",
    "Title" -> "Hodgkins", "RowsCount" -> 43, "ColumnsCount" -> 6,
    "NumericColumnsCount" -> 6, "CharacterColumnsCount" -> 0|>,
  <|"Package" -> "Statistics", "Item" -> "IBMStockClosingPrices",
    "Title" -> "IBMStockClosingPrices", "RowsCount" -> 369, "ColumnsCount" -> 1,
    "NumericColumnsCount" -> 1, "CharacterColumnsCount" -> 0|>,
  <|"Package" -> "Statistics", "Item" -> "IndomethicinPharmacokinetics",
    "Title" -> "Indomethicin Pharmacokinetics", "RowsCount" -> 66, "ColumnsCount" -> 3,
    "NumericColumnsCount" -> 2, "CharacterColumnsCount" -> 1|>,
  <|"Package" -> "Statistics", "Item" -> "InternationalAirlinePassengers",
    "Title" -> "InternationalAirlinePassengers", "RowsCount" -> 12, "ColumnsCount" -> 13,
    "NumericColumnsCount" -> 13, "CharacterColumnsCount" -> 0|>,
  <|"Package" -> "Statistics", "Item" -> "KaleDDT", "Title" -> "Kale DDT",
    "RowsCount" -> 15, "ColumnsCount" -> 1, "NumericColumnsCount" -> 1,
    "CharacterColumnsCount" -> 0|>, <|"Package" -> "Statistics",
    "Item" -> "KidneyInfection", "Title" -> "Kidney Infection", "RowsCount" -> 119,
    "ColumnsCount" -> 3, "NumericColumnsCount" -> 3, "CharacterColumnsCount" -> 0|>,
  <|"Package" -> "Statistics", "Item" -> "KidneyTransplant",
    "Title" -> "Kidney Transplant", "RowsCount" -> 863, "ColumnsCount" -> 5,
    "NumericColumnsCount" -> 5, "CharacterColumnsCount" -> 0|>,
  <|"Package" -> "Statistics", "Item" -> "LakeMeadLevels",
    "Title" -> "Lake Mead Levels", "RowsCount" -> 75, "ColumnsCount" -> 13,
    "NumericColumnsCount" -> 13, "CharacterColumnsCount" -> 0|>,
  <|"Package" -> "Statistics", "Item" -> "LarynxCancer", "Title" -> "Larynx Cancer",
    "RowsCount" -> 90, "ColumnsCount" -> 5, "NumericColumnsCount" -> 5,
    "CharacterColumnsCount" -> 0|>, <|"Package" -> "Statistics",
    "Item" -> "LifeCycleSavings", "Title" -> "Life Cycle Savings", "RowsCount" -> 50,
    "ColumnsCount" -> 5, "NumericColumnsCount" -> 5, "CharacterColumnsCount" -> 0|>,
  <|"Package" -> "Statistics", "Item" -> "LoblollyTreeGrowth",
    "Title" -> "Loblolly Tree Growth", "RowsCount" -> 83, "ColumnsCount" -> 3,
    "NumericColumnsCount" -> 2, "CharacterColumnsCount" -> 1|>,
  <|"Package" -> "Statistics", "Item" -> "LosAngelesOzoneReadings",
    "Title" -> "LosAngelesOzoneReadings", "RowsCount" -> 18, "ColumnsCount" -> 13,
    "NumericColumnsCount" -> 13, "CharacterColumnsCount" -> 0|>,
  <|"Package" -> "Statistics", "Item" -> "MahanadiRiverFlow",
    "Title" -> "Mahanadi River Flow", "RowsCount" -> 22, "ColumnsCount" -> 1,
    "NumericColumnsCount" -> 1, "CharacterColumnsCount" -> 0|>,
  <|"Package" -> "Statistics", "Item" -> "MarkTwainAuthorship",
    "Title" -> "Mark Twain Authorship", "RowsCount" -> 13, "ColumnsCount" -> 3,
    "NumericColumnsCount" -> 3, "CharacterColumnsCount" -> 0|>,
  <|"Package" -> "Statistics", "Item" -> "MercuryVaporPressure",
    "Title" -> "Mercury Vapor Pressure", "RowsCount" -> 19, "ColumnsCount" -> 2,
    "NumericColumnsCount" -> 2, "CharacterColumnsCount" -> 0|>,
  <|"Package" -> "Statistics", "Item" -> "MinkFurSales", "Title" -> "MinkFurSales",
    "RowsCount" -> 62, "ColumnsCount" -> 1, "NumericColumnsCount" -> 1,
    "CharacterColumnsCount" -> 0|>, <|"Package" -> "Statistics",
    "Item" -> "MotorFailures", "Title" -> "Motor Failures", "RowsCount" -> 40,
    "ColumnsCount" -> 3, "NumericColumnsCount" -> 3, "CharacterColumnsCount" -> 0|>,
  <|"Package" -> "Statistics", "Item" -> "NewcombLightSpeed",
    "Title" -> "Newcomb Light Speed", "RowsCount" -> 66, "ColumnsCount" -> 1,
    "NumericColumnsCount" -> 1, "CharacterColumnsCount" -> 0|>,
  <|"Package" -> "Statistics", "Item" -> "NickelContent", "Title" -> "Nickel Content",
    "RowsCount" -> 31, "ColumnsCount" -> 1, "NumericColumnsCount" -> 1,
    "CharacterColumnsCount" -> 0|>, <|"Package" -> "Statistics", "Item" -> "OldFaithful",
    "Title" -> "Old Faithful", "RowsCount" -> 272, "ColumnsCount" -> 2,
    "NumericColumnsCount" -> 2, "CharacterColumnsCount" -> 0|>,
  <|"Package" -> "Statistics", "Item" -> "OrangeTreeGrowth",
    "Title" -> "Orange Tree Growth", "RowsCount" -> 35, "ColumnsCount" -> 3,
    "NumericColumnsCount" -> 2, "CharacterColumnsCount" -> 1|>,
  <|"Package" -> "Statistics", "Item" -> "OtitisMedia", "Title" -> "Otitis Media",
    "RowsCount" -> 220, "ColumnsCount" -> 5, "NumericColumnsCount" -> 1,
    "CharacterColumnsCount" -> 4|>, <|"Package" -> "Statistics",
    "Item" -> "OzoneConcentrations", "Title" -> "Ozone Concentrations",
    "RowsCount" -> 284, "ColumnsCount" -> 3, "NumericColumnsCount" -> 1,
    "CharacterColumnsCount" -> 2|>, <|"Package" -> "Statistics", "Item" -> "PlantGrowth",
    "Title" -> "Plant Growth", "RowsCount" -> 30, "ColumnsCount" -> 2,
    "NumericColumnsCount" -> 1, "CharacterColumnsCount" -> 1|>,
  <|"Package" -> "Statistics", "Item" -> "Psychiatric", "Title" -> "Psychiatric",
    "RowsCount" -> 26, "ColumnsCount" -> 4, "NumericColumnsCount" -> 4,
    "CharacterColumnsCount" -> 0|>, <|"Package" -> "Statistics",
    "Item" -> "PuromycinReactionVelocity", "Title" -> "Puromycin Reaction Velocity",
    "RowsCount" -> 23, "ColumnsCount" -> 3, "NumericColumnsCount" -> 2,
    "CharacterColumnsCount" -> 1|>, <|"Package" -> "Statistics",
    "Item" -> "QuarterlyRevenue", "Title" -> "Quarterly Revenue", "RowsCount" -> 39,
    "ColumnsCount" -> 5, "NumericColumnsCount" -> 5, "CharacterColumnsCount" -> 0|>,
  <|"Package" -> "Statistics", "Item" -> "RainfallSeeding",
    "Title" -> "Rainfall Seeding", "RowsCount" -> 52, "ColumnsCount" -> 2,
    "NumericColumnsCount" -> 1, "CharacterColumnsCount" -> 1|>,
  <|"Package" -> "Statistics", "Item" -> "RiverLengths", "Title" -> "River Lengths",
    "RowsCount" -> 141, "ColumnsCount" -> 1, "NumericColumnsCount" -> 1,
    "CharacterColumnsCount" -> 0|>, <|"Package" -> "Statistics",
    "Item" -> "ScientificDiscoveries", "Title" -> "Scientific Discoveries",
    "RowsCount" -> 100, "ColumnsCount" -> 1, "NumericColumnsCount" -> 1,
    "CharacterColumnsCount" -> 0|>, <|"Package" -> "Statistics",
    "Item" -> "ScottishHillRaces", "Title" -> "Scottish Hill Races", "RowsCount" -> 35,
    "ColumnsCount" -> 4, "NumericColumnsCount" -> 3, "CharacterColumnsCount" -> 1|>,
  <|"Package" -> "Statistics", "Item" -> "SingerHeights", "Title" -> "Singer Heights",
    "RowsCount" -> 235, "ColumnsCount" -> 2, "NumericColumnsCount" -> 1,
    "CharacterColumnsCount" -> 1|>, <|"Package" -> "Statistics",
    "Item" -> "SoporificDrugs", "Title" -> "Soporific Drugs", "RowsCount" -> 20,
    "ColumnsCount" -> 3, "NumericColumnsCount" -> 1, "CharacterColumnsCount" -> 2|>,
  <|"Package" -> "Statistics", "Item" -> "SP500",
    "Title" -> "Standard and Poor's 500", "RowsCount" -> 2780, "ColumnsCount" -> 1,
    "NumericColumnsCount" -> 1, "CharacterColumnsCount" -> 0|>,
  <|"Package" -> "Statistics", "Item" -> "SpeedOfLight", "Title" -> "Speed Of Light",
    "RowsCount" -> 100, "ColumnsCount" -> 3, "NumericColumnsCount" -> 1,
    "CharacterColumnsCount" -> 2|>, <|"Package" -> "Statistics",
    "Item" -> "StacklossPlant", "Title" -> "Stackloss Plant", "RowsCount" -> 21,
    "ColumnsCount" -> 4, "NumericColumnsCount" -> 4, "CharacterColumnsCount" -> 0|>,
  <|"Package" -> "Statistics", "Item" -> "SwissBankNotes",
    "Title" -> "Swiss Bank Notes", "RowsCount" -> 200, "ColumnsCount" -> 7,
    "NumericColumnsCount" -> 7, "CharacterColumnsCount" -> 0|>,
  <|"Package" -> "Statistics", "Item" -> "SwissFertility", "Title" -> "Swiss Fertility",
    "RowsCount" -> 47, "ColumnsCount" -> 6, "NumericColumnsCount" -> 6,
    "CharacterColumnsCount" -> 0|>, <|"Package" -> "Statistics", "Item" -> "Terrorism",
    "Title" -> "Terrorism", "RowsCount" -> 9101, "ColumnsCount" -> 1,
    "NumericColumnsCount" -> 1, "CharacterColumnsCount" -> 0|>,
  <|"Package" -> "Statistics", "Item" -> "TimeToAIDS", "Title" -> "Time to AIDS",
    "RowsCount" -> 295, "ColumnsCount" -> 3, "NumericColumnsCount" -> 3,
    "CharacterColumnsCount" -> 0|>, <|"Package" -> "Statistics",
    "Item" -> "TopOilFields2001", "Title" -> "Top Oil Fields 2001", "RowsCount" -> 116,
    "ColumnsCount" -> 3, "NumericColumnsCount" -> 1, "CharacterColumnsCount" -> 2|>,
  <|"Package" -> "Statistics", "Item" -> "UgandaVolcanoes",
    "Title" -> "Uganda Volcanoes", "RowsCount" -> 120, "ColumnsCount" -> 2,
    "NumericColumnsCount" -> 2, "CharacterColumnsCount" -> 0|>,
  <|"Package" -> "Statistics", "Item" -> "UKLungDiseaseDeaths",
    "Title" -> "UK Lung-Disease Deaths", "RowsCount" -> 72, "ColumnsCount" -> 1,
    "NumericColumnsCount" -> 1, "CharacterColumnsCount" -> 0|>,
  <|"Package" -> "Statistics", "Item" -> "UKUnemployment", "Title" -> "UKUnemployment",
    "RowsCount" -> 60, "ColumnsCount" -> 4, "NumericColumnsCount" -> 4,
    "CharacterColumnsCount" -> 0|>, <|"Package" -> "Statistics",
    "Item" -> "UniversitySalaries", "Title" -> "University Salaries",
    "RowsCount" -> 25438, "ColumnsCount" -> 4, "NumericColumnsCount" -> 2,
    "CharacterColumnsCount" -> 2|>, <|"Package" -> "Statistics",
    "Item" -> "USAccidentalDeaths", "Title" -> "US Accidental Deaths", "RowsCount" -> 72,
    "ColumnsCount" -> 1, "NumericColumnsCount" -> 1, "CharacterColumnsCount" -> 0|>,
  <|"Package" -> "Statistics", "Item" -> "USArrests", "Title" -> "US Arrests",
    "RowsCount" -> 50, "ColumnsCount" -> 5, "NumericColumnsCount" -> 4,
    "CharacterColumnsCount" -> 1|>, <|"Package" -> "Statistics", "Item" -> "USCars1993",
    "Title" -> "US Cars 1993", "RowsCount" -> 93, "ColumnsCount" -> 26,
    "NumericColumnsCount" -> 19, "CharacterColumnsCount" -> 7|>,
  <|"Package" -> "Statistics", "Item" -> "USCityTemperature",
    "Title" -> "US City Temperature", "RowsCount" -> 360, "ColumnsCount" -> 4,
    "NumericColumnsCount" -> 1, "CharacterColumnsCount" -> 3|>,
  <|"Package" -> "Statistics", "Item" -> "USEarthquakes", "Title" -> "US Earthquakes",
    "RowsCount" -> 3567, "ColumnsCount" -> 7, "NumericColumnsCount" -> 7,
    "CharacterColumnsCount" -> 0|>, <|"Package" -> "Statistics", "Item" -> "USHogPrices",
    "Title" -> "USHogPrices", "RowsCount" -> 82, "ColumnsCount" -> 2,
    "NumericColumnsCount" -> 2, "CharacterColumnsCount" -> 0|>,
  <|"Package" -> "Statistics", "Item" -> "USHurricaneLoss",
    "Title" -> "US Hurricane Loss", "RowsCount" -> 30, "ColumnsCount" -> 4,
    "NumericColumnsCount" -> 3, "CharacterColumnsCount" -> 1|>,
  <|"Package" -> "Statistics", "Item" -> "USLifeTable2003",
    "Title" -> "US Life Table 2003", "RowsCount" -> 101, "ColumnsCount" -> 8,
    "NumericColumnsCount" -> 8, "CharacterColumnsCount" -> 0|>,
  <|"Package" -> "Statistics", "Item" -> "USStateIncome", "Title" -> "US State Income",
    "RowsCount" -> 50, "ColumnsCount" -> 2, "NumericColumnsCount" -> 1,
    "CharacterColumnsCount" -> 1|>, <|"Package" -> "Statistics", "Item" -> "WarpBreaks",
    "Title" -> "Warp Breaks", "RowsCount" -> 54, "ColumnsCount" -> 3,
    "NumericColumnsCount" -> 1, "CharacterColumnsCount" -> 2|>,
  <|"Package" -> "Statistics", "Item" -> "WesternUgandaBorder",
    "Title" -> "Western Uganda Border", "RowsCount" -> 396, "ColumnsCount" -> 2,
    "NumericColumnsCount" -> 2, "CharacterColumnsCount" -> 0|>,
  <|"Package" -> "Statistics", "Item" -> "WolfSunspotNumbers",
    "Title" -> "WolfSunspotNumbers", "RowsCount" -> 100, "ColumnsCount" -> 1,
    "NumericColumnsCount" -> 1, "CharacterColumnsCount" -> 0|>},
  TypeSystem`Vector[TypeSystem`Struct[{"Package", "Item", "Title", "RowsCount",
    "ColumnsCount", "NumericColumnsCount", "CharacterColumnsCount"},
    {TypeSystem`Atom[String], TypeSystem`Atom[String], TypeSystem`Atom[String],
      TypeSystem`Atom[Integer], TypeSystem`Atom[Integer], TypeSystem`Atom[Integer],
      TypeSystem`Atom[Integer]}], 111], <||>];
